import type { AllergySeverity, AllergyType, ClinicalRecordCategory } from "@prisma/client";
import { AlertTriangle, ShieldCheck } from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/components/carelux-ui";
import type { getResidentHealth } from "@/modules/resident-clinical/server/get-resident-health";

import { BrowserDateTime } from "./browser-date-time";
import { AllergyDialog, ClinicalRecordDialog, DiagnosisDialog } from "./clinical-entry-forms";
import { DeactivateAllergyDialog, DeactivateDiagnosisDialog, VoidClinicalRecordDialog } from "./clinical-status-actions";

type HealthData = Awaited<ReturnType<typeof getResidentHealth>>;
type ResidentHealthProps = HealthData & { residentId: string };

const dateFormatter = new Intl.DateTimeFormat("pt-PT", { dateStyle: "medium" });
const severityLabels: Record<AllergySeverity, string> = { MILD: "Ligeira", MODERATE: "Moderada", SEVERE: "Grave", LIFE_THREATENING: "Risco de vida" };
const typeLabels: Record<AllergyType, string> = { MEDICATION: "Medicamento", FOOD: "Alimento", ENVIRONMENTAL: "Ambiental", CONTACT: "Contacto", OTHER: "Outro" };
const categoryLabels: Record<ClinicalRecordCategory, string> = { MEDICAL: "Medicina", NURSING: "Enfermagem", PHYSIOTHERAPY: "Fisioterapia", OCCUPATIONAL_THERAPY: "Terapia ocupacional", SPEECH_THERAPY: "Terapia da fala", PSYCHOLOGY: "Psicologia", NUTRITION: "Nutrição", SOCIAL_WORK: "Serviço social", AUDIOLOGY: "Audiologia", OTHER: "Outro" };

function EmptyMessage({ children }: { children: string }) {
  return <p className="rounded-xl border border-dashed border-border px-4 py-6 text-center text-sm text-muted-foreground">{children}</p>;
}

function Author({ user }: { user: { fullName: string; role: { name: string } } }) {
  return <span>{user.fullName}<span className="text-muted-foreground"> · {user.role.name}</span></span>;
}

export function ResidentHealth({ residentId, diagnoses, allergies, clinicalRecords, alerts, authorization }: ResidentHealthProps) {
  const activeDiagnoses = diagnoses.filter((item) => item.status === "ACTIVE");
  const inactiveDiagnoses = diagnoses.filter((item) => item.status === "INACTIVE");
  const diagnosisNamesById = new Map(diagnoses.map((item) => [item.id, item.name]));
  const correctionNamesByDiagnosisId = new Map(diagnoses.flatMap((item) => item.supersedesId ? [[item.supersedesId, item.name] as const] : []));
  const activeAllergies = allergies.filter((item) => item.status === "ACTIVE");
  const inactiveAllergies = allergies.filter((item) => item.status === "INACTIVE");
  const allergyNamesById = new Map(allergies.map((item) => [item.id, item.allergen]));
  const correctionNamesByAllergyId = new Map(allergies.flatMap((item) => item.supersedesId ? [[item.supersedesId, item.allergen] as const] : []));

  return <div className="space-y-5">
    <section aria-labelledby="clinical-alerts-title" className={`rounded-2xl border p-5 shadow-sm ${alerts.length ? "border-destructive/25 bg-destructive/5" : "border-primary/20 bg-primary/5"}`}>
      <div className="flex items-start gap-3"><span className={`flex size-11 shrink-0 items-center justify-center rounded-xl ${alerts.length ? "bg-destructive/10 text-destructive" : "bg-primary/10 text-primary"}`}>{alerts.length ? <AlertTriangle aria-hidden size={22} /> : <ShieldCheck aria-hidden size={22} />}</span><div className="min-w-0"><h2 id="clinical-alerts-title" className="text-sm font-semibold text-foreground">Alertas clínicos</h2>{alerts.length ? <><p className="mt-1 text-sm text-muted-foreground">Alergias ativas que exigem atenção acrescida.</p><ul className="mt-4 grid gap-3 md:grid-cols-2">{alerts.map((allergy) => <li key={allergy.id} className="rounded-xl border border-destructive/20 bg-card p-4"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm text-foreground">{allergy.allergen}</strong><span className="rounded-full bg-destructive/10 px-2.5 py-1 text-xs font-semibold text-destructive">{severityLabels[allergy.severity]}</span></div><p className="mt-2 text-sm text-muted-foreground">Reação: {allergy.reaction}</p></li>)}</ul></> : <p className="mt-1 text-sm text-muted-foreground">Sem alergias graves ou com risco de vida ativas.</p>}</div></div>
    </section>

    <section aria-labelledby="diagnoses-title"><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Patologias</p><CardTitle id="diagnoses-title" className="mt-1">Diagnósticos</CardTitle></div>{authorization.canEditDiagnoses && <DiagnosisDialog residentId={residentId} />}</div></CardHeader><CardContent className="space-y-5">
      {activeDiagnoses.length ? <ul className="grid gap-3 lg:grid-cols-2">{activeDiagnoses.map((item) => <li key={item.id} className="rounded-xl border border-border bg-background/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-foreground">{item.name}</h3><p className="mt-1 text-xs text-muted-foreground">{item.diagnosedAt ? dateFormatter.format(item.diagnosedAt) : "Data não indicada"} · <Author user={item.createdBy} /></p>{item.supersedesId && diagnosisNamesById.has(item.supersedesId) && <p className="mt-1 text-xs text-muted-foreground">Correção de: <span className="font-medium text-foreground">{diagnosisNamesById.get(item.supersedesId)}</span></p>}</div><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">Ativo</span></div>{item.description && <p className="mt-3 text-sm leading-5 text-foreground">{item.description}</p>}{item.observations && <p className="mt-2 text-sm text-muted-foreground">{item.observations}</p>}{authorization.canEditDiagnoses && <div className="mt-4 flex flex-wrap gap-2"><DiagnosisDialog residentId={residentId} diagnosis={item} /><DeactivateDiagnosisDialog residentId={residentId} diagnosisId={item.id} /></div>}</li>)}</ul> : <EmptyMessage>Não existem diagnósticos ativos.</EmptyMessage>}
      {inactiveDiagnoses.length > 0 && <details className="group rounded-xl border border-border"><summary className="interactive-target cursor-pointer px-4 py-3 text-sm font-semibold text-foreground">Histórico de diagnósticos ({inactiveDiagnoses.length})</summary><ul className="border-t border-border px-4 py-2">{inactiveDiagnoses.map((item) => <li key={item.id} className="border-b border-border/70 py-3 last:border-0"><div className="flex flex-wrap justify-between gap-2"><span className="text-sm font-semibold text-foreground">{item.name}</span><span className="text-xs text-muted-foreground">Inativo</span></div>{item.supersedesId && diagnosisNamesById.has(item.supersedesId) && <p className="mt-1 text-xs text-muted-foreground">Correção de: <span className="font-medium text-foreground">{diagnosisNamesById.get(item.supersedesId)}</span></p>}{correctionNamesByDiagnosisId.has(item.id) && <p className="mt-1 text-xs text-muted-foreground">Substituído por: <span className="font-medium text-foreground">{correctionNamesByDiagnosisId.get(item.id)}</span></p>}{item.deactivatedBy && item.deactivatedAt && <p className="mt-1 text-xs text-muted-foreground">Desativado por: <Author user={item.deactivatedBy} /> · <BrowserDateTime value={item.deactivatedAt.toISOString()} /></p>}</li>)}</ul></details>}
    </CardContent></Card></section>

    <section aria-labelledby="allergies-title"><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Segurança clínica</p><CardTitle id="allergies-title" className="mt-1">Alergias</CardTitle></div>{authorization.canEditAllergies && <AllergyDialog residentId={residentId} />}</div></CardHeader><CardContent className="space-y-5">
      {activeAllergies.length ? <ul className="grid gap-3 lg:grid-cols-2">{activeAllergies.map((item) => <li key={item.id} className="rounded-xl border border-border bg-background/70 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-foreground">{item.allergen}</h3><p className="mt-1 text-xs text-muted-foreground">{item.type ? typeLabels[item.type] : "Tipo não indicado"} · <Author user={item.createdBy} /></p>{item.supersedesId && allergyNamesById.has(item.supersedesId) && <p className="mt-1 text-xs text-muted-foreground">Correção de: <span className="font-medium text-foreground">{allergyNamesById.get(item.supersedesId)}</span></p>}</div><span className="rounded-full bg-secondary/20 px-2.5 py-1 text-xs font-semibold text-foreground">{severityLabels[item.severity]}</span></div><p className="mt-3 text-sm text-foreground"><span className="font-semibold">Reação:</span> {item.reaction}</p>{item.observations && <p className="mt-2 text-sm text-muted-foreground">{item.observations}</p>}{authorization.canEditAllergies && <div className="mt-4 flex flex-wrap gap-2"><AllergyDialog residentId={residentId} allergy={item} /><DeactivateAllergyDialog residentId={residentId} allergyId={item.id} /></div>}</li>)}</ul> : <EmptyMessage>Não existem alergias ativas.</EmptyMessage>}
      {inactiveAllergies.length > 0 && <details className="rounded-xl border border-border"><summary className="interactive-target cursor-pointer px-4 py-3 text-sm font-semibold text-foreground">Histórico de alergias ({inactiveAllergies.length})</summary><ul className="border-t border-border px-4 py-2">{inactiveAllergies.map((item) => <li key={item.id} className="border-b border-border/70 py-3 last:border-0"><div className="flex flex-wrap justify-between gap-2"><div><span className="text-sm font-semibold text-foreground">{item.allergen}</span><p className="mt-1 text-xs text-muted-foreground">{item.type ? typeLabels[item.type] : "Tipo não indicado"} · <Author user={item.createdBy} /></p></div><span className="text-xs text-muted-foreground">{severityLabels[item.severity]} · Inativa</span></div><p className="mt-2 text-sm text-foreground"><span className="font-semibold">Reação:</span> {item.reaction}</p>{item.observations && <p className="mt-1 text-sm text-muted-foreground">{item.observations}</p>}{item.supersedesId && allergyNamesById.has(item.supersedesId) && <p className="mt-1 text-xs text-muted-foreground">Correção de: <span className="font-medium text-foreground">{allergyNamesById.get(item.supersedesId)}</span></p>}{correctionNamesByAllergyId.has(item.id) && <p className="mt-1 text-xs text-muted-foreground">Substituído por: <span className="font-medium text-foreground">{correctionNamesByAllergyId.get(item.id)}</span></p>}{item.deactivatedBy && item.deactivatedAt && <p className="mt-1 text-xs text-muted-foreground">Desativada por: <Author user={item.deactivatedBy} /> · <BrowserDateTime value={item.deactivatedAt.toISOString()} /></p>}</li>)}</ul></details>}
    </CardContent></Card></section>

    <section aria-labelledby="records-title"><Card><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-primary">Dossier cronológico</p><CardTitle id="records-title" className="mt-1">Histórico clínico</CardTitle></div>{authorization.canEditClinicalRecords && <ClinicalRecordDialog residentId={residentId} />}</div></CardHeader><CardContent>
      {clinicalRecords.length ? <ol className="relative space-y-4 before:absolute before:bottom-3 before:left-[0.68rem] before:top-3 before:w-px before:bg-border">{clinicalRecords.map((record) => <li key={record.id} className="relative pl-9"><span className={`absolute left-0 top-1.5 size-[1.4rem] rounded-full border-4 border-card ${record.status === "VOIDED" ? "bg-muted-foreground" : "bg-primary"}`} /><article className={`rounded-xl border p-4 ${record.status === "VOIDED" ? "border-border bg-muted/40" : "border-border bg-background/70"}`}><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{categoryLabels[record.category]}</span>{record.status === "VOIDED" && <span className="rounded-full bg-muted px-2.5 py-1 text-xs font-semibold text-muted-foreground">Anulado</span>}{record.amendsRecordId && <span className="text-xs font-semibold text-muted-foreground">Correção</span>}</div><h3 className="mt-2 font-semibold text-foreground">{record.title}</h3>{record.amendsRecord && <p className="mt-1 text-xs text-muted-foreground">Correção de: <span className="font-medium text-foreground">{record.amendsRecord.title}</span> · <BrowserDateTime value={record.amendsRecord.clinicalAt.toISOString()} />{record.amendsRecord.status === "VOIDED" && " · Original anulado"}</p>}</div><BrowserDateTime className="text-xs text-muted-foreground" value={record.clinicalAt.toISOString()} /></div><p className={`mt-3 whitespace-pre-wrap text-sm leading-6 ${record.status === "VOIDED" ? "text-muted-foreground line-through decoration-muted-foreground/40" : "text-foreground"}`}>{record.content}</p><div className="mt-4 flex flex-col gap-1 border-t border-border/70 pt-3 text-xs text-muted-foreground"><span><Author user={record.authorUser} /></span><span>Proveniência: {record.facility.name}</span>{record.status === "VOIDED" && record.voidedBy && record.voidedAt && <span>Anulado por: <Author user={record.voidedBy} /> · <BrowserDateTime value={record.voidedAt.toISOString()} /></span>}{record.status === "VOIDED" && record.voidReason && <span>Motivo da anulação: {record.voidReason}</span>}</div>{authorization.canEditClinicalRecords && record.status === "ACTIVE" && <div className="mt-4 flex flex-wrap gap-2"><ClinicalRecordDialog residentId={residentId} record={record} /><VoidClinicalRecordDialog residentId={residentId} recordId={record.id} /></div>}</article></li>)}</ol> : <EmptyMessage>Não existem registos clínicos.</EmptyMessage>}
    </CardContent></Card></section>
  </div>;
}
