export enum Permission {
  VIEW_RESIDENT = "VIEW_RESIDENT",
  CREATE_RESIDENT = "CREATE_RESIDENT",
  EDIT_RESIDENT = "EDIT_RESIDENT",
  ARCHIVE_RESIDENT = "ARCHIVE_RESIDENT",

  VIEW_CLINICAL_RECORD = "VIEW_CLINICAL_RECORD",
  EDIT_PATHOLOGY = "EDIT_PATHOLOGY",
  VIEW_MEDICATION = "VIEW_MEDICATION",
  EDIT_MEDICATION = "EDIT_MEDICATION",
  VIEW_APPOINTMENT = "VIEW_APPOINTMENT",
  EDIT_APPOINTMENT = "EDIT_APPOINTMENT",

  VIEW_DOCUMENT = "VIEW_DOCUMENT",
  CREATE_DOCUMENT = "CREATE_DOCUMENT",
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT",
  PRINT_DOCUMENT = "PRINT_DOCUMENT",

  VIEW_EMPLOYEES = "VIEW_EMPLOYEES",
  EDIT_EMPLOYEES = "EDIT_EMPLOYEES",

  VIEW_FINANCE = "VIEW_FINANCE",
  EDIT_FINANCE = "EDIT_FINANCE",

  VIEW_INVENTORY = "VIEW_INVENTORY",
  EDIT_INVENTORY = "EDIT_INVENTORY",
  CREATE_INVENTORY_REQUEST = "CREATE_INVENTORY_REQUEST",
  PROCESS_INVENTORY_REQUEST = "PROCESS_INVENTORY_REQUEST",

  MANAGE_USERS = "MANAGE_USERS",
  VIEW_AUDIT = "VIEW_AUDIT",
  EXPORT_DATA = "EXPORT_DATA",
  VIEW_FAMILY = "VIEW_FAMILY",
  SEND_MESSAGES = "SEND_MESSAGES",
}
