export enum Permission {

  // Residentes
  VIEW_RESIDENT = "VIEW_RESIDENT",
  CREATE_RESIDENT = "CREATE_RESIDENT",
  EDIT_RESIDENT = "EDIT_RESIDENT",
  ARCHIVE_RESIDENT = "ARCHIVE_RESIDENT",

  // Processo Clínico
  VIEW_CLINICAL_RECORD = "VIEW_CLINICAL_RECORD",
  EDIT_CLINICAL_RECORD = "EDIT_CLINICAL_RECORD",

  // Medicação
  VIEW_MEDICATION = "VIEW_MEDICATION",
  EDIT_MEDICATION = "EDIT_MEDICATION",

  // Documentos
  VIEW_DOCUMENT = "VIEW_DOCUMENT",
  CREATE_DOCUMENT = "CREATE_DOCUMENT",
  DELETE_DOCUMENT = "DELETE_DOCUMENT",
  DOWNLOAD_DOCUMENT = "DOWNLOAD_DOCUMENT",
  PRINT_DOCUMENT = "PRINT_DOCUMENT",

  // Funcionários
  VIEW_EMPLOYEES = "VIEW_EMPLOYEES",
  EDIT_EMPLOYEES = "EDIT_EMPLOYEES",

  // Financeiro
  VIEW_FINANCE = "VIEW_FINANCE",
  EDIT_FINANCE = "EDIT_FINANCE",

  // Utilizadores
  MANAGE_USERS = "MANAGE_USERS",

  // Auditoria
  VIEW_AUDIT = "VIEW_AUDIT",

  // Exportação
  EXPORT_DATA = "EXPORT_DATA",

  // Família
  VIEW_FAMILY = "VIEW_FAMILY",
  SEND_MESSAGES = "SEND_MESSAGES",
}