export enum Role {
  ADMIN = "ADMIN",

  CLIENT_ADMIN = "CLIENT_ADMIN",

  DIRECTOR = "DIRECTOR",

  DOCTOR = "DOCTOR",

  NURSE = "NURSE",

  PHYSIOTHERAPIST = "PHYSIOTHERAPIST",

  PSYCHOLOGIST = "PSYCHOLOGIST",

  OCCUPATIONAL_THERAPIST = "OCCUPATIONAL_THERAPIST",

  SPEECH_THERAPIST = "SPEECH_THERAPIST",

  SOCIAL_WORKER = "SOCIAL_WORKER",

  CAREGIVER = "CAREGIVER",

  RECEPTIONIST = "RECEPTIONIST",

  ADMINISTRATIVE = "ADMINISTRATIVE",

  FAMILY = "FAMILY",

  EXTERNAL_AUDITOR = "EXTERNAL_AUDITOR",
}